#!/sbin/busybox sh

# Reset LED bar
busybox echo '0' > /sys/class/leds/l-key-red/brightness
busybox echo '0' > /sys/class/leds/l-key-green/brightness
busybox echo '0' > /sys/class/leds/l-key-blue/brightness
busybox echo '0' > /sys/class/leds/m-key-red/brightness
busybox echo '0' > /sys/class/leds/m-key-green/brightness
busybox echo '0' > /sys/class/leds/m-key-blue/brightness
busybox echo '0' > /sys/class/leds/r-key-red/brightness
busybox echo '0' > /sys/class/leds/r-key-green/brightness
busybox echo '0' > /sys/class/leds/r-key-blue/brightness

# In animaton
for i in $(seq 0 3 255)
do
    busybox echo $i > /sys/class/leds/l-key-red/brightness
    busybox echo $i > /sys/class/leds/m-key-red/brightness
    busybox echo $i > /sys/class/leds/r-key-red/brightness
done 

for i in $(seq 0 3 255)
do
    busybox echo $i > /sys/class/leds/l-key-green/brightness
    busybox echo $i > /sys/class/leds/m-key-green/brightness
    busybox echo $i > /sys/class/leds/r-key-green/brightness
done 

for i in $(seq 0 3 255)
do
    j=$((255 - $i))
    
    busybox echo $j > /sys/class/leds/l-key-red/brightness
    busybox echo $j > /sys/class/leds/m-key-red/brightness
    busybox echo $j > /sys/class/leds/r-key-red/brightness
done

# Trigger vibration
busybox echo '50' > /sys/class/timed_output/vibrator/enable

# Out animaton
for i in $(seq 0 3 255)
do
    j=$((255 - $i))
    
    busybox echo $j > /sys/class/leds/l-key-green/brightness
    busybox echo $j > /sys/class/leds/m-key-green/brightness
    busybox echo $j > /sys/class/leds/r-key-green/brightness
done



